### ISSUE TITLE
Add Python bindings?

### ISSUE THREAD

**Issue by AntoinePrv** [conda-forge/benchmark-feedstock#15]
Hello,

Google benchmark supports some (minimal but hopefully growing) [Python bindings](https://github.com/google/benchmark/tree/master/bindings/python).
They are shipped on PyPI under the name [google-benchmark](https://pypi.org/project/google-benchmark/).

I was wondering if it could be relevant to add them to this repository, or maybe to create a new one.

 Thanks!

**Comment by xhochy** [comment]
Please create a new one, that should be simpler to maintain.
